web/router.ex
defmodule SponsorDotDog.Router do
  use SponsorDotDog.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", SponsorDotDog do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/states/:state_abbreviation", StateController, :show
    resources "/pet_rescues", PetRescueController, only: [:index, :show , :create], param: "rescue_id"
    resources "/dogs", DogController, only: [:index, :show, :create], param: "pet_id"
  end

  # Other scopes may use custom stacks.
  # scope "/api", SponsorDotDog do
  #   pipe_through :api
  # end
end

lib/sponsor_dot_dog/endpoint.ex
defmodule SponsorDotDog.Endpoint do
  use Phoenix.Endpoint, otp_app: :sponsor_dot_dog

  socket "/socket", SponsorDotDog.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :sponsor_dot_dog, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  plug Plug.Session,
    store: :cookie,
    key: "_sponsor_dot_dog_key",
    signing_salt: "26AA1OEV"

  plug SponsorDotDog.Router
end

lib/sponsor_dot_dog/repo.ex
defmodule SponsorDotDog.Repo do
  use Ecto.Repo, otp_app: :sponsor_dot_dog
end

web/models/dog.ex
defmodule SponsorDotDog.Dog do
  use SponsorDotDog.Web, :model

  schema "dogs" do
    field :pet_id, :string
    field :name, :string
    field :animal, :string
    field :mix, :string
    field :age, :string
    field :sex, :string
    field :options, :string
    field :description, :string
    field :last_update, Ecto.Date
    field :photo_1, :string
    field :photo_2, :string
    belongs_to :rescue, SponsorDotDog.Rescue

    timestamps
  end

  @required_fields ~w(pet_id name animal description last_update)
  @optional_fields ~w(mix age sex options photo_1 photo_2)

  @doc """
  Creates a changeset based on the `model` and `params`.

  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
  end
end

web/models/pet_rescue.ex
defmodule SponsorDotDog.PetRescue do
  use SponsorDotDog.Web, :model

  schema "petrescues" do
    field :rescue_id, :string
    field :rescue_name, :string
    field :address1, :string
    field :address2, :string
    field :city, :string
    field :zip, :string
    field :country, :string
    field :phone, :string
    field :fax, :string
    field :email, :string
    belongs_to :state, SponsorDotDog.State
    has_many :dogs, SponsorDotDog.Dog


    timestamps
  end

  @required_fields ~w(rescue_id rescue_name address1 city zip)
  @optional_fields ~w(address2 country phone fax email)

  @doc """
  Creates a changeset based on the `model` and `params`.

  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
  end
end

web/models/state.ex
defmodule SponsorDotDog.State do
  use SponsorDotDog.Web, :model

  schema "states" do
    field :state_abbreviation, :string
    field :state_name, :string
    field :state_group, :integer

    has_many :pet_rescues, SponsorDotDog.PetRescue

    timestamps
  end

  @required_fields ~w(state_abbreviation state_name)
  @optional_fields ~w()

  @doc """
  Creates a changeset based on the `model` and `params`.

  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
  end
end

web/controllers/dog_controller.ex
defmodule SponsorDotDog.DogController do
  use SponsorDotDog.Web, :controller

  alias SponsorDotDog.Dog

  plug :scrub_params, "dog" when action in [:create, :update]

  def create(conn, %{"dog" => dog_params}) do
    changeset = Dog.changeset(%Dog{}, dog_params)

    case Repo.insert(changeset) do
      {:ok, _dog} ->
        conn
        |> put_flash(:info, "Dog created successfully.")
        |> redirect(to: pet_rescue_path(conn, :show, dog_params.rescue_id))
      {:error, _dog} ->
        conn
        |> put_flash(:error, "There was an error.")
        |> redirect(to: pet_rescue_path(conn, :index))
    end
  end

  def index(conn, params) do
    render(conn, "index.html", dog_id: params["dog_id"])
  end

  def show(conn, %{"pet_id" => pet_id}) do
    dog = Repo.get!(Dog, pet_id: pet_id)
    render(conn, "show.html", dog: dog)
  end

end

web/controllers/page_controller.ex
defmodule SponsorDotDog.PageController do
  use SponsorDotDog.Web, :controller

  alias SponsorDotDog.State

  def index(conn, _params) do
    states = Repo.all(State)
    render(conn, "index.html", states: states)
  end
end

web/controllers/pet_rescue_controller.ex
defmodule SponsorDotDog.PetRescueController do
  use SponsorDotDog.Web, :controller

  alias SponsorDotDog.PetRescue

  plug :scrub_params, "pet_rescue" when action in [:create, :update]

  def create(conn, %{"pet_rescue" => pet_rescue_params}) do
    changeset = PetRescue.changeset(%PetRescue{}, pet_rescue_params)

    case Repo.insert(changeset) do
      {:ok, _pet_rescue} ->
        conn
        |> put_flash(:info, "Pet rescue created successfully.")
        |> redirect(to: pet_rescue_path(conn, :show, pet_rescue_params.id))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def index(conn, params) do
    render(conn, "index.html", shelter_id: params["shelter"])
  end

  def show(conn, %{"rescue_id" => rescue_id}) do
    exists = Repo.get(PetRescue, rescue_id: rescue_id)
    if exists do
      pet_rescue = Repo.get!(PetRescue, rescue_id: rescue_id)
      state = Repo.get!(State, pet_rescue.state_id)
      render(conn, "show.html", pet_rescue: pet_rescue, state: state)
    else
      render(conn, "show.html")
    end
  end

end

web/controllers/state_controller.ex
defmodule SponsorDotDog.StateController do
  use SponsorDotDog.Web, :controller

  alias SponsorDotDog.State
  alias SponsorDotDog.PetRescue

  def show(conn, %{"state_abbreviation" => state_abbreviation}) do
    state = Repo.get_by!(State, state_abbreviation: state_abbreviation)
    pet_rescues = Repo.all(from p in PetRescue, where: p.state_id == ^state.id)
    render(conn, "show.html", state: state, pet_rescues: pet_rescues)
  end

end

web/views/dog_view.ex
defmodule SponsorDotDog.DogView do
  use SponsorDotDog.Web, :view
end

web/views/error_view.ex
defmodule SponsorDotDog.ErrorView do
  use SponsorDotDog.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Server internal error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule SponsorDotDog.LayoutView do
  use SponsorDotDog.Web, :view
end

web/views/page_view.ex
defmodule SponsorDotDog.PageView do
  use SponsorDotDog.Web, :view
end

web/views/pet_rescue_view.ex
defmodule SponsorDotDog.PetRescueView do
  use SponsorDotDog.Web, :view
end

web/views/state_view.ex
defmodule SponsorDotDog.StateView do
  use SponsorDotDog.Web, :view
end

web/templates/dog/index.html.eex
<style>
.carousel-container {
  background-color: #dfdfdf;
  border-radius: 10px;
  padding: 1em 0;
}
</style>
<div class="container-fluid">
  <div class="col-xs-12">
    <button class="btn btn-primary" onclick="window.history.back()">Back to State</button>
    <center><h2></h2></center>
    <div class="col-lg-12 carousel-container">
      <div class="col-lg-6 col-lg-offset-3">
        <div class="carousel">
        </div>
      </div>
    </div>
    <div class="col-lg-6">
      <table class="table table-rounded table1">
        <thead>
          <th>Details:</th>
          <th>&nbsp;</th>
        </thead>
      </table>
    </div>
    <div class="col-lg-6">
      <table class="table table-rounded table2">
      </table>
    </div>
  </div>
</div>
<script type="text/javascript">
window.onload = function() {
  var url = "http://api.petfinder.com/pet.get?format=json&key=<%= Application.get_env(:sponsor_dot_dog, :petfinder_key) %>&count=50&id=<%= @dog_id %>&callback=?";

  $.ajax(url, {
    dataType: 'jsonp',
    success: function(data) {
      console.log(data);
      var pet = data.petfinder.pet;
      $("h2").append(pet.name.$t);
      for (i = 0; i < pet.media.photos.photo.length; i++) {
        var imageArray = $.map(pet.media.photos.photo[i], function(value, index) {
          return [value];
        });
        if (imageArray[0] == "pn") {
          var img = "<img src='" + imageArray[1] + "' />" ;
          $(".carousel").append(img);
        }
      }
      if ($.isEmptyObject(pet.age) == false) {
        $(".table1").append("<tr><td>Age:</td><td>"+ pet.age.$t + "</td></tr>");
      }
      if (pet.breeds.breed.length == null) {
        $(".table1").append("<tr><td>Breed:</td><td>" + pet.breeds.breed.$t + "</td></tr>");
      } else {
        var breeds = "";
        $.each(pet.breeds.breed, function(t, val) {
          breeds += val.$t + "<br/>";
        });
        $(".table1").append("<tr><td>Breeds:</td><td>" + breeds + "</td></tr>");
      }
      if ($.isEmptyObject(pet.options) == false){
        if (pet.options.option.length == null) {
          $(".table1").append("<tr><td>Options:</td><td>" + pet.options.option.$t + "</td></tr>");
        } else {
          var options = "";
          for (t = 0; t < pet.options.option.length; t++) {
            if (pet.options.option[t].$t != "altered") {
              options += pet.options.option[t].$t + "<br/>";
            }
          }
          $(".table1").append("<tr><td>Options:</td><td>" + options + "</td></tr>");
        }
      }
      if ($.isEmptyObject(pet.description) == false) {
        $(".table2").append("<thead><th>Age:</th></thead><tbody><td>" + pet.description.$t.replace(/\n/g,"<br>") + "</td></tbody>");
      }
      $(".carousel").slick({
        lazyLoad: 'progressive',
        dots: true,
        speed: 300,
        slidesToShow: 1,
        adaptiveHeight: true
      });
    }
  });

};
</script>

web/templates/dog/show.html.eex
<h2>Show dog</h2>

<ul>

  <li>
    <strong>Pet:</strong>
    <%= @dog.pet_id %>
  </li>

  <li>
    <strong>Rescue:</strong>
    <%= @dog.rescue_id %>
  </li>

  <li>
    <strong>Name:</strong>
    <%= @dog.name %>
  </li>

  <li>
    <strong>Animal:</strong>
    <%= @dog.animal %>
  </li>

  <li>
    <strong>Mix:</strong>
    <%= @dog.mix %>
  </li>

  <li>
    <strong>Age:</strong>
    <%= @dog.age %>
  </li>

  <li>
    <strong>Sex:</strong>
    <%= @dog.sex %>
  </li>

  <li>
    <strong>Options:</strong>
    <%= @dog.options %>
  </li>

  <li>
    <strong>Description:</strong>
    <%= @dog.description %>
  </li>

  <li>
    <strong>Last update:</strong>
    <%= @dog.last_update %>
  </li>

  <li>
    <strong>Photo 1:</strong>
    <%= @dog.photo_1 %>
  </li>

  <li>
    <strong>Photo 2:</strong>
    <%= @dog.photo_2 %>
  </li>

</ul>

<%= link "Back to Pet Rescue", to: pet_rescue_path(@conn, :show, @dog.rescue_id) %>

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Sponsor.Dog</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <a href="<%= page_path(@conn, :index) %>">
          <span class="logo"></span>
        </a>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/page/index.html.eex
<p class="center">
  Please pick a state:
</p>
<div style="margin:auto" id="visualization"></div>

<div class="jumbotron">
</div>

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">
google.charts.load('current', {'packages':['geochart']});
google.charts.setOnLoadCallback(drawVisualization);
function drawVisualization() {
  var data = google.visualization.arrayToDataTable([
    ['State','Group'],
    <%= for state <- @states do %>
    ['<%= state.state_abbreviation %>',<%= state.state_group %>],
    <%= end %>
    ]);

  var geochart = new google.visualization.GeoChart(
      document.getElementById('visualization'));
  var options = {
    legend: 'none',
    tooltip: {trigger: 'none'},
    width: '100%',
    height: 347,
    region: "US",
    resolution: "provinces",
    colorAxis: {
      values: [1,2,3,4,5],
      colors: ['#663399', '#66ccff', '#99cc99', '#ff9966', '#ffff99']
    }
  };
  geochart.draw(data, options);

  google.visualization.events.addListener(geochart, 'select', function () {
    var selection = geochart.getSelection();
    var row = selection[0].row;
    var url = data.getValue(row, 0);
    window.open(window.location.href + 'states/' + url, "_parent");
   });
}
</script>

web/templates/pet_rescue/index.html.eex
<button class="btn btn-primary" onclick="window.history.back()">Back to State</button>
<div class="nav">
  <ul class="pager">
  </ul>
</div>
<table class="table table-hover table-rounded">
  <thead class="titles">
    <th><center>Main Image</center></th>
    <th>Name</th>
    <th>Age</th>
    <th>Gender</th>
    <th>Breeds</th>
    <th>Notes</th>
  </thead>
</table>
<button class="btn btn-primary" onclick="window.history.back()">Back to State</button>
<script type=text/javascript>
var count = "25";
var callback = "&callback=?";
var urlStart = "http://api.petfinder.com/shelter.getPets?format=json&key=<%= Application.get_env(:sponsor_dot_dog, :petfinder_key) %>&id=<%= @shelter_id %>&count=";
function loadPets(newOffset) {
  var newOffset = (typeof newOffset === 'undefined') ? 0 : newOffset;
  var offset = "&offset=" + newOffset;
  var url = urlStart + count + offset + callback;
  $("table tr").not("table thead tr").remove();
  $(".pager li").remove();
  $.ajax(url, {
    dataType: 'jsonp',
    success: function(data) {
      console.log(data);
      if (data.petfinder.lastOffset.$t == count && (data.petfinder.lastOffset.$t % count) == 0) {
        $(".pager").append("<li><a onclick='loadPets(" + count + ")'>Next " + count + "</a></li>");
      } else if (data.petfinder.lastOffset.$t > count && (data.petfinder.lastOffset.$t % count) == 0) {
        $(".pager").append("<li><a onclick='loadPets(" + (newOffset - count) + ");'>Prev " + count + "</a></li>");
        $(".pager").append("<li><a onclick='loadPets(" + data.petfinder.lastOffset.$t + ");'>Next " + count + "</a></li>");
      } else if (Number(data.petfinder.lastOffset.$t) > Number(count)) {
        offsetRemainder = data.petfinder.lastOffset.$t % count;
        prevOffset = data.petfinder.lastOffset.$t - offsetRemainder - count;
        $(".pager").append("<li><a onclick='loadPets(" + prevOffset + ")'>Prev</a></li>");
      }
      var dogs = false;
      // No parsing necessary.
      pet_list = data.petfinder.pets.pet;
      for (i = 0; i < pet_list.length; i++) {
        if (pet_list[i].animal.$t != "Dog") { break; }
        dogs = true;
        var name = pet_list[i].name.$t == null ? '' : pet_list[i].name.$t;
        var age = pet_list[i].age.$t   == null ? '' : pet_list[i].age.$t;
        var gender = pet_list[i].sex.$t   == null ? '' : pet_list[i].sex.$t;
        var breed = "";
        if (pet_list[i].breeds.breed.length == null) {
          breed += pet_list[i].breeds.breed.$t + "<br/>";
        } else {
          $.each(pet_list[i].breeds.breed, function(t, val) {
            breed += val.$t + "<br/>";
          });
        }
        var image = "";
        if ($.isEmptyObject(pet_list[i].media.photos) == false){
          image += pet_list[i].media.photos.photo[3].$t;
        }
        var options = "";
        if ($.isEmptyObject(pet_list[i].options) == false){
          if (pet_list[i].options.option.length == null) {
            options += pet_list[i].options.option.$t + "<br/>";
          } else {
            for (t = 0; t < pet_list[i].options.option.length; t++) {
              if (pet_list[i].options.option[t].$t != "altered") {
                options += pet_list[i].options.option[t].$t + "<br/>";
              }
            }
          }
        }
        var dogId = pet_list[i].id.$t;
        tr = $('<tr onclick=\'window.open("'+ window.location.origin + '/dogs/?dog_id=' + dogId +'","_self")\'/>');
        tr.append("<td style='text-align:center;'><img style='padding:1em;height:200px;' src='" + image + "'/></td>");
        tr.append("<td>" + name + "</td>");
        tr.append("<td>" + age + "</td>");
        tr.append("<td>" + gender + "</td>");
        tr.append("<td>" + breed + "</td>");
        tr.append("<td>" + options + "</td>");
        $('table').append(tr);
      }
      if (dogs == false) {
        var noDogs = "<div class='jumbotron'><h2>This shelter doesn't have any dogs!</h2></div>";
        $('body').append(noDogs);
      }
    }
  });
}
window.onload = function() {
  loadPets();
}
</script>

web/templates/pet_rescue/show.html.eex
<h2>Show pet rescue</h2>

<ul>

  <li>
    <strong>Rescue:</strong>
    <%= @pet_rescue.rescue_id %>
  </li>

  <li>
    <strong>Rescue name:</strong>
    <%= @pet_rescue.rescue_name %>
  </li>

  <li>
    <strong>Address1:</strong>
    <%= @pet_rescue.address1 %>
  </li>

  <li>
    <strong>Address2:</strong>
    <%= @pet_rescue.address2 %>
  </li>

  <li>
    <strong>City:</strong>
    <%= @pet_rescue.city %>
  </li>

  <li>
    <strong>State:</strong>
    <%= @pet_rescue.state_id %>
  </li>

  <li>
    <strong>Zip:</strong>
    <%= @pet_rescue.zip %>
  </li>

  <li>
    <strong>Country:</strong>
    <%= @pet_rescue.country %>
  </li>

  <li>
    <strong>Phone:</strong>
    <%= @pet_rescue.phone %>
  </li>

  <li>
    <strong>Fax:</strong>
    <%= @pet_rescue.fax %>
  </li>

  <li>
    <strong>Email:</strong>
    <%= @pet_rescue.email %>
  </li>

</ul>
<div class="col-lg-12">
  <h4 class="text-center"> You are looking at dogs from <%= @pet_rescue.rescue_name %> </h4>
</div>

<ul/>
<table class="table table-striped col-lg-12">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>City</th>
    </tr>
  </thead>
</table>
<script type="text/javascript">
window.onload = function() {
  var url = "http://api.petfinder.com/shelter.getPets?format=json&key=<%= Application.get_env(:sponsor_dot_dog, :petfinder_key) %>&id=<%= @pet_rescue.rescue_id %>&callback=?";

  $.ajax(url, {
    dataType: 'jsonp',
    success: function(data) {
      // No parsing necessary.
      console.log(data)
      // shelter_list = data.petfinder.shelters.shelter;
      // var arr = [];
      // for (i = 0; i < shelter_list.length; i++) {
      //   console.log(shelter_list[i].id.$t);
      //   console.log(shelter_list[i].name.$t);
      //   console.log(shelter_list[i].address1.$t);
      //   console.log(shelter_list[i].address2.$t);
      //   console.log(shelter_list[i].city.$t + ", " + shelter_list[i].state.$t + " " + shelter_list[i].zip.$t);
      //   console.log(shelter_list[i].phone.$t);
      //   console.log(shelter_list[i].email.$t);
      //   console.log("----------------");
      //   var name = shelter_list[i].name.$t         == null ? '' : shelter_list[i].name.$t;
      //   var address1 = shelter_list[i].address1.$t == null ? '' : shelter_list[i].address1.$t;
      //   var address2 = shelter_list[i].address2.$t == null ? '' : shelter_list[i].address2.$t;
      //   var city = shelter_list[i].city.$t         == null ? '' : shelter_list[i].city.$t;
      //   var state = shelter_list[i].state.$t       == null ? '' : shelter_list[i].state.$t;
      //   var zip = shelter_list[i].zip.$t           == null ? '' : shelter_list[i].zip.$t;
      //   var phone = shelter_list[i].phone.$t       == null ? '' : shelter_list[i].phone.$t;
      //   var email = shelter_list[i].email.$t       ==  null? '' : shelter_list[i].email.$t;
      //   tr = $('<tr/>');
      //   tr.append("<td>" + name + "</td>");
      //   tr.append("<td>" + address1 + '<br/>' + address2 + "</td>");
      //   tr.append("<td>" + city + '<br/>' + state + ' ' + zip + "</td>");
      //   $('table').append(tr);
      // }
    }
  });
}
</script>

<%= #link "Back to State List", to: state_path(@conn, :show, @state.state_abbreviation) %>

web/templates/state/show.html.eex
<div class="col-lg-12">
  <%= link "Back to Home", to: page_path(@conn, :index) %>
  <h4 class="text-center"> You are looking at rescues from <%= @state.state_name %> </h4>
</div>

<ul>
  <%= for pet_rescue <- @pet_rescues do %>
  <li>
    <%= pet_rescue.rescue_name %>
  </li>
  <%= end %>
</ul>

<div class="nav">
  <ul class="pager">
  </ul>
</div>

</ul>
<table class="table table-striped col-lg-12">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>City</th>
      <th>Contact</th>
    </tr>
  </thead>
</table>
<%= link "Back to Home", to: page_path(@conn, :index) %>

<script type="text/javascript">
var count = "100";
var callback = "&callback=?";
var urlStart = "http://api.petfinder.com/shelter.find?format=json&key=<%= Application.get_env(:sponsor_dot_dog, :petfinder_key) %>&location=<%= @state.state_abbreviation %>&count=";

function loadShelters(newOffset) {
  var newOffset = (typeof newOffset === 'undefined') ? 0 : newOffset;
  var offset = "&offset=" + newOffset;
  var url = urlStart + count + offset + callback;
  $.ajax(url, {
    dataType: 'jsonp',
    success: function(data) {
      $("table tr").not("table thead tr").remove();
      $(".pager li").remove();
      console.log(data);
      if (Number(data.petfinder.lastOffset.$t) == Number(count) && (Number(data.petfinder.lastOffset.$t) % Number(count)) == 0) {
        $(".pager").append("<li><a onclick='loadShelters(" + data.petfinder.lastOffset.$t + ")'>Next " + count + "</a></li>");
      } else if (Number(data.petfinder.lastOffset.$t) > Number(count) && (Number(data.petfinder.lastOffset.$t) % Number(count)) == 0) {
        $(".pager").append("<li><a onclick='loadShelters(" + (newOffset - count) + ");'>Prev " + count + "</a></li>");
        $(".pager").append("<li><a onclick='loadShelters(" + data.petfinder.lastOffset.$t + ");'>Next " + count + "</a></li>");
      } else if (Number(data.petfinder.lastOffset.$t) > Number(count)) {
        offsetRemainder = data.petfinder.lastOffset.$t % count;
        prevOffset = data.petfinder.lastOffset.$t - offsetRemainder - count;
        $(".pager").append("<li><a onclick='loadShelters(" + prevOffset + ")'>Prev</a></li>");
      }
      shelter_list = data.petfinder.shelters.shelter;
      for (i = 0; i < shelter_list.length; i++) {
        var name = shelter_list[i].name.$t         == null ? '' : shelter_list[i].name.$t;
        var address1 = shelter_list[i].address1.$t == null ? '' : shelter_list[i].address1.$t;
        var address2 = shelter_list[i].address2.$t == null ? '' : shelter_list[i].address2.$t;
        var city = shelter_list[i].city.$t         == null ? '' : shelter_list[i].city.$t;
        var state = shelter_list[i].state.$t       == null ? '' : shelter_list[i].state.$t;
        var zip = shelter_list[i].zip.$t           == null ? '' : shelter_list[i].zip.$t;
        var phone = shelter_list[i].phone.$t       == null ? '' : shelter_list[i].phone.$t;
        var email = shelter_list[i].email.$t       ==  null? '' : shelter_list[i].email.$t;
        tr = $('<tr/>');
        tr.append("<td>" + name + "</td>");
        tr.append("<td>" + address1 + '<br/>' + address2 + "</td>");
        tr.append("<td>" + city + '<br/>' + state + ' ' + zip + "</td>");
        tr.append("<td>" + phone + '<br/>' + email + "</td>");
        tr.append("<td>" + '<a class="btn btn-primary" href="' + window.location.origin + '/pet_rescues/?shelter=' + shelter_list[i].id.$t + '">See animals</a>' + "</td>");
        $('table').append(tr);
      }
    }
  });
}
window.onload = function() {
  loadShelters();
}
</script>